"""add payment

Revision ID: 392e2835740a
Revises: 83233069f672
Create Date: 2025-10-13 21:13:17.709065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392e2835740a'
down_revision: Union[str, Sequence[str], None] = '83233069f672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_lessons', sa.Column('payment', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('students', sa.Column('paid', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'paid')
    op.drop_column('student_lessons', 'payment')
    # ### end Alembic commands ###
