"""fix tables

Revision ID: 9f94273d17eb
Revises: 357043a8665d
Create Date: 2025-10-08 08:42:12.344864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f94273d17eb'
down_revision: Union[str, Sequence[str], None] = '357043a8665d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('user_roles_association', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_roles_association_role_fkey'), 'user_roles_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles_association', 'roles', ['role_id'], ['id'])
    op.drop_column('user_roles_association', 'role')
    op.alter_column('users', 'date_joined',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_joined',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('user_roles_association', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_roles_association', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_association_role_fkey'), 'user_roles_association', 'roles', ['role'], ['id'])
    op.drop_column('user_roles_association', 'role_id')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
