"""add utc column for user

Revision ID: 3e31744bccb4
Revises: 392e2835740a
Create Date: 2025-10-15 17:08:07.350838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e31744bccb4'
down_revision: Union[str, Sequence[str], None] = '392e2835740a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timedelta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timedelta')
    # ### end Alembic commands ###
